In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("IMDB Dataset.csv")

In [7]:
df.head(20)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
5   Probably my all-time favorite movie, a story o...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing, fresh & innovative i...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Boll's work but then ag...  negative
13  The cast played Shakespeare.<br /><br />Shakes...  negative
14  This a fantastic movie of three prisoners who ...  positive
15  Kind of drawn in by the erotic scenes, only to...  negative
16  Some films just simply should not be remade. T...  positive
17  This movie made it into one of my top 10 most ...  negative
18  I remember this film,it was the first film i h...  positive
19  An awful film! It must have been up against so...  negative

In [8]:
print(df["review"][0])

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [10]:
df["review"] = df["review"].str.lower()

In [11]:
import re

def remove_html(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

df["review"] = df["review"].apply(remove_html)

In [12]:
import string

punc = string.punctuation

def remove_punc(text):
    for char in punc:
        text = text.replace(char, '')
    return text

df["review"] = df["review"].apply(remove_punc)

In [13]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

df["review"] = df["review"].apply(remove_url)

In [14]:
chat_word = {
    'AFAIK': 'As Far As I Know',
    'AFK': 'Away From Keyboard',
    'ASAP': 'As Soon As Possible',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'BRB': 'Be Right Back',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'B4': 'Before',
    'B4N': 'Bye For Now',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FAQ': 'Frequently Asked Questions',
    'FC': 'Fingers Crossed',
    'FWIW': 'For What It\'s Worth',
    'FYI': 'For Your Information',
    'GAL': 'Get A Life',
    'GG': 'Good Game',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek you (also a chat program)',
    'ILU': 'I Love You',
    'IMHO': 'In My Honest/Humble Opinion',
    'IMO': 'In My Opinion',
    'IOW': 'In Other Words',
    'IRL': 'In Real Life',
    'KISS': 'Keep It Simple, Stupid',
    'LDR': 'Long Distance Relationship',
    'LMAO': 'Laugh My A.. Off',
    'LOL': 'Laughing Out Loud',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'M8': 'Mate',
    'NGL': 'Not Going to lie',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The A..',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'QPSA': 'Que Pasa?',
    'ROFL': 'Rolling On The Floor Laughing',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My A.. Off',
    'SK8': 'Skate',
    'STATS': 'Your sex and age',
    'ASL': 'Age, Sex, Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'TTYL': 'Talk To You Later',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The F...',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait...',
    '7K': 'Sick:-D Laughter',
    'TFW': 'That feeling when',
    'MFW': 'My face when',
    'MRW': 'My reaction when',
    'IFYP': 'I feel your pain',
    'LOL': 'Laughing out loud',
    'TNTL': 'Trying not to laugh',
    'JK': 'Just kidding',
    'IDC': 'I don’t care',
    'ILY': 'I love you',
    'IMU': 'I miss you',
    'ADIH': 'Another day in hell',
    'IDC': 'I don’t care',
    'ZZZ': 'Sleeping, bored, tired',
    'WYWH': 'Wish you were here',
    'TIME': 'Tears in my eyes',
    'BAE': 'Before anyone else',
    'FIMH': 'Forever in my heart',
    'BSAAW': 'Big smile and a wink',
    'BWL': 'Bursting with laughter',
    'LMAO': 'Laughing my a** off',
    'BFF': 'Best friends forever',
    'CSL': 'Can’t stop laughing'
}

In [15]:
def chat_treat(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_word:
            new_text.append(chat_word[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

df["review"] = df["review"].apply(chat_treat)

Spelling Correction

In [36]:
from textblob import TextBlob

def spell_check(text):
    spell = TextBlob(text)
    return spell.correct().string

df["review"] = df["review"].apply(spell_check)

KeyboardInterrupt:

In [58]:

def normalize_words(text):
    # replace repeated characters (more than 2 → 2)
    return re.sub(r'(.)\1{2,}', r'\1\1', text)

df["review"] = df["review"].apply(normalize_words)

Stop Words Removal

In [59]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))


def removewords(text):
    new = []
    for w in text.split():
        if w not in stop_words:
            new.append(w)
    return " ".join(new)

df["review"] = df["review"].apply(removewords)

Tokenization

In [60]:
from nltk.tokenize import word_tokenize

df["token"] = (df["review"]).apply(word_tokenize)

lemmitization

In [61]:
from nltk.stem import WordNetLemmatizer

lem = WordNetLemmatizer()

def word_lem(text):
    new = []
    for w in text:
        new.append(lem.lemmatize(w,pos='v'))
    return " ".join(new)

df["token"] = df["token"].apply(word_lem)

Coupus Count and Vocab Count

In [62]:
df.head(20)

,review,sentiment,token,clean_text
0,one reviewers mentioned watching 1 oz episode ...,positive,one reviewers mention watch 1 oz episode youll...,one reviewers mention watch oz episode youll ...
1,wonderful little production filming technique ...,positive,wonderful little production film technique una...,wonderful little production film technique una...
2,thought wonderful way spend Tears eyes hot sum...,positive,think wonderful way spend Tears eye hot summer...,think wonderful way spend tears eye hot summer...
3,basically theres family little boy jake thinks...,negative,basically theres family little boy jake think ...,basically theres family little boy jake think ...
4,petter matteis love Tears eyes money visually ...,positive,petter matteis love Tears eye money visually s...,petter matteis love tears eye money visually s...
5,probably alltime favorite movie story selfless...,positive,probably alltime favorite movie story selfless...,probably alltime favorite movie story selfless...
6,sure would like see resurrection dated seahunt...,positive,sure would like see resurrection date seahunt ...,sure would like see resurrection date seahunt ...
7,show amazing fresh innovative idea 70s first a...,negative,show amaze fresh innovative idea 70s first air...,show amaze fresh innovative idea s first air f...
8,encouraged positive comments film looking forw...,negative,encourage positive comment film look forward w...,encourage positive comment film look forward w...
9,like original gut wrenching laughter like movi...,positive,like original gut wrench laughter like movie y...,like original gut wrench laughter like movie y...
10,phil alien one quirky films humour based aroun...,negative,phil alien one quirky film humour base around ...,phil alien one quirky film humour base around ...
11,saw movie 12 came recall scariest scene big bi...,negative,saw movie 12 come recall scariest scene big bi...,saw movie come recall scariest scene big bird...
12,im big fan bolls work many enjoyed movie posta...,negative,im big fan bolls work many enjoy movie postal ...,im big fan bolls work many enjoy movie postal ...
13,cast played shakespeareshakespeare losti appre...,negative,cast play shakespeareshakespeare losti appreci...,cast play shakespeareshakespeare losti appreci...
14,fantastic movie three prisoners become famous ...,positive,fantastic movie three prisoners become famous ...,fantastic movie three prisoners become famous ...
15,kind drawn erotic scenes realize one amateuris...,negative,kind draw erotic scenes realize one amateurish...,kind draw erotic scenes realize one amateurish...
16,films simply remade one bad film fails capture...,positive,film simply remake one bad film fail capture f...,film simply remake one bad film fail capture f...
17,movie made one top 10 awful movies horrible wa...,negative,movie make one top 10 awful movies horrible wa...,movie make one top awful movies horrible wasn...
18,remember filmit first film watched cinema pict...,positive,remember filmit first film watch cinema pictur...,remember filmit first film watch cinema pictur...
19,awful film must real stinkers nominated golden...,negative,awful film must real stinkers nominate golden ...,awful film must real stinkers nominate golden ...

In [63]:
word_count = 0
for text in df["token"]:
    word_count += len(text.split())
    
print(word_count)

6023099

In [64]:
import re

def clean_text(text):
    # remove special/control characters
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)
    
    # remove numbers
    text = re.sub(r'\d+', '', text)
    
    # remove punctuation (optional)
    text = re.sub(r'[^\w\s]', '', text)
    
    # lowercase
    text = text.lower()
    
    return text

df["clean_text"] = df["token"].apply(clean_text)

In [69]:
vocab = set()

for text in df["clean_text"]:
    vocab.update(text.split())

vocab = sorted(vocab)
print(len(vocab))

200998

One Hot Encoding

In [71]:
word2idx = {word: i for i, word in enumerate(vocab)}

word2idx = {}

for i, word in enumerate(vocab):
    word2idx[word] = i

In [72]:
word2idx

{'a': 0,
 'aa': 1,
 'aab': 2,
 'aachen': 3,
 'aada': 4,
 'aadha': 5,
 'aadmittedly': 6,
 'aag': 7,
 'aage': 8,
 'aagghh': 9,
 'aagh': 10,
 'aaghh': 11,
 'aaghi': 12,
 'aah': 13,
 'aahemy': 14,
 'aahh': 15,
 'aahhgg': 16,
 'aahthe': 17,
 'aaila': 18,
 'aailiyah': 19,
 'aaip': 20,
 'aaja': 21,
 'aajala': 22,
 'aak': 23,
 'aakash': 24,
 'aake': 25,
 'aaker': 26,
 'aakrosh': 27,
 'aalcc': 28,
 'aaliyah': 29,
 'aaliyahs': 30,
 'aall': 31,
 'aalox': 32,
 'aames': 33,
 'aamess': 34,
 'aamesthe': 35,
 'aamilne': 36,
 'aamir': 37,
 'aamirs': 38,
 'aamirsalmanraveenakarishma': 39,
 'aamirso': 40,
 'aamr': 41,
 'aan': 42,
 'aand': 43,
 'aankh': 44,
 'aankhen': 45,
 'aaoon': 46,
 'aap': 47,
 'aapke': 48,
 'aapkey': 49,
 'aaran': 50,
 'aardman': 51,
 'aardmans': 52,
 'aardmanthe': 53,
 'aardvark': 54,
 'aardvarks': 55,
 'aarf': 56,
 'aargh': 57,
 'aarghhow': 58,
 'aarghlets': 59,
 'aarika': 60,
 'aaron': 61,
 'aarona': 62,
 'aaronanchors': 63,
 'aaroncurb': 64,
 'aaronjd': 65,
 'aarons': 66,
 'aaronwho': 67,
 'aarp': 68,
 'aarrgghh': 69,
 'aarrgh': 70,
 'aarrghim': 71,
 'aashok': 72,
 'aasize': 73,
 'aasmaan': 74,
 'aasman': 75,
 'aatchkah': 76,
 'aatish': 77,
 'aaton': 78,
 'aau': 79,
 'aaugh': 80,
 'aauugghh': 81,
 'aavjo': 82,
 'aaw': 83,
 'aawip': 84,
 'aaww': 85,
 'ab': 86,
 'ababy': 87,
 'aback': 88,
 'abagail': 89,
 'abahy': 90,
 'abanazer': 91,
 'abandon': 92,
 'abandoningindian': 93,
 'abandonment': 94,
 'abandonmentshe': 95,
 'abandonof': 96,
 'abanks': 97,
 'abas': 98,
 'abash': 99,
 'abashidze': 100,
 'abate': 101,
 'abatement': 102,
 'abattoirs': 103,
 'abba': 104,
 'abbad': 105,
 'abbas': 106,
 'abbasi': 107,
 'abbasmustan': 108,
 'abbastyle': 109,
 'abbe': 110,
 'abbey': 111,
 'abbeys': 112,
 'abbeythe': 113,
 'abbie': 114,
 'abbot': 115,
 'abbotcameron': 116,
 'abbotcostello': 117,
 'abbots': 118,
 'abbott': 119,
 'abbottcostello': 120,
 'abbottok': 121,
 'abbotts': 122,
 'abbottwe': 123,
 'abbottwhich': 124,
 'abbreviate': 125,
 'abbu': 126,
 'abby': 127,
 'abbys': 128,
 'abbyshe': 129,
 'abbyss': 130,
 'abc': 131,
 'abcafterschoolspecial': 132,
 'abccbsnbc': 133,
 'abccom': 134,
 'abcd': 135,
 'abcrelease': 136,
 'abcs': 137,
 'abcsears': 138,
 'abcthe': 139,
 'abctv': 140,
 'abcwe': 141,
 'abd': 142,
 'abdalla': 143,
 'abderrahmane': 144,
 'abdic': 145,
 'abdicate': 146,
 'abdomen': 147,
 'abdominal': 148,
 'abdoo': 149,
 'abduct': 150,
 'abductedi': 151,
 'abductednot': 152,
 'abductee': 153,
 'abduction': 154,
 'abductionman': 155,
 'abductions': 156,
 'abductiontype': 157,
 'abductor': 158,
 'abductors': 159,
 'abduhamdi': 160,
 'abdul': 161,
 'abdullah': 162,
 'abdulrahman': 163,
 'abe': 164,
 'abecassis': 165,
 'abed': 166,
 'abedalla': 167,
 'abedded': 168,
 'abel': 169,
 'abell': 170,
 'abels': 171,
 'abemethie': 172,
 'abercrombie': 173,
 'abercrombiefitch': 174,
 'aberdeen': 175,
 'aberdeenst': 176,
 'abernathie': 177,
 'abernathies': 178,
 'abernathy': 179,
 'abernethie': 180,
 'aberrant': 181,
 'aberration': 182,
 'aberrationeye': 183,
 'aberrations': 184,
 'aberystwyth': 185,
 'abet': 186,
 'abeyance': 187,
 'abfab': 188,
 'abgail': 189,
 'abhay': 190,
 'abhays': 191,
 'abhi': 192,
 'abhijeet': 193,
 'abhijeetrehan': 194,
 'abhimaan': 195,
 'abhisheh': 196,
 'abhishek': 197,
 'abhisheks': 198,
 'abhor': 199,
 'abhorent': 200,
 'abhorrd': 201,
 'abhorrence': 202,
 'abhorrent': 203,
 'abhorrentthen': 204,
 'abi': 205,
 'abide': 206,
 'abigail': 207,
 'abigails': 208,
 'abigil': 209,
 'abilene': 210,
 'abilities': 211,
 'abilitiesi': 212,
 'abilitiesif': 213,
 'abilitieskahn': 214,
 'abilitiespaul': 215,
 'abilitiesprobably': 216,
 'abilitiesput': 217,
 'abilitiessome': 218,
 'abilitiesthe': 219,
 'abilitiesthere': 220,
 'abilitiesunfortunately': 221,
 'abilitiesyou': 222,
 'ability': 223,
 'abilityhbk': 224,
 'abilityi': 225,
 'abilityit': 226,
 'abilitymost': 227,
 'abilityno': 228,
 'abilityof': 229,
 'abilitys': 230,
 'abilitysadly': 231,
 'abilitytalent': 232,
 'abilitythe': 233,
 'abilitythere': 234,
 'abilitythroughout': 235,
 'abilitywhat': 236,
 'abingdon': 237,
 'abirrd': 238,
 'abishag': 239,
 'abishai': 240,
 'abishek': 241,
 'abisheks': 242,
 'abit': 243,
 'abitmorethanlight': 244,
 'abject': 245,
 'abjectly': 246,
 'abkani': 247,
 'ablank': 248,
 'ablaze': 249,
 'ablazeso': 250,
 'ablazin': 251,
 'able': 252,
 'ableand': 253,
 'ablebodied': 254,
 'abler': 255,
 'ables': 256,
 'ablest': 257,
 'ablethey': 258,
 'ableto': 259,
 'ablibs': 260,
 'ablities': 261,
 'ably': 262,
 'ablybut': 263,
 'abm': 264,
 'abnegate': 265,
 'abnegation': 266,
 'abner': 267,
 'abnerguys': 268,
 'abnormal': 269,
 'abnormality': 270,
 'abnormally': 271,
 'abo': 272,
 'aboard': 273,
 'aboardnot': 274,
 'abodelab': 275,
 'abodes': 276,
 'abolish': 277,
 'abolition': 278,
 'abolitiongate': 279,
 'abolitionism': 280,
 'abolitionist': 281,
 'abolitionists': 282,
 'abomb': 283,
 'abombnew': 284,
 'abombs': 285,
 'abomin': 286,
 'abominable': 287,
 'abominably': 288,
 'abominal': 289,
 'abomination': 290,
 'abominationif': 291,
 'abominationits': 292,
 'abominations': 293,
 'abominationsupermans': 294,
 'abominator': 295,
 'abominibal': 296,
 'abondons': 297,
 'aboot': 298,
 'aboout': 299,
 'aboreson': 300,
 'aborigin': 301,
 'aboriginal': 302,
 'aboriginals': 303,
 'aborigine': 304,
 'aboriginebut': 305,
 'aboriginee': 306,
 'aborigines': 307,
 'aboriginies': 308,
 'aborigins': 309,
 'aborigone': 310,
 'abort': 311,
 'abortedi': 312,
 'abortion': 313,
 'abortionist': 314,
 'abortionistlots': 315,
 'abortionnot': 316,
 'abortions': 317,
 'abortionthe': 318,
 'abortive': 319,
 'abos': 320,
 'abott': 321,
 'abou': 322,
 'abound': 323,
 'aboundafter': 324,
 'aboundand': 325,
 'aboundbottom': 326,
 'aboundclint': 327,
 'aboundcoming': 328,
 'abounddays': 329,
 'aboundseverything': 330,
 'aboundsnot': 331,
 'aboundsthis': 332,
 'aboundthe': 333,
 'aboundthird': 334,
 'aboundtoday': 335,
 'about': 336,
 'abouta': 337,
 'aboutafter': 338,
 'aboutagirly': 339,
 'aboutalice': 340,
 'aboutall': 341,
 'aboutalso': 342,
 'aboutamerican': 343,
 'aboutand': 344,
 'aboutanother': 345,
 'aboutanyway': 346,
 'aboutapart': 347,
 'aboutarent': 348,
 'aboutas': 349,
 'aboutat': 350,
 'aboutavp': 351,
 'aboutbeauty': 352,
 'aboutbeing': 353,
 'aboutbest': 354,
 'aboutbiko': 355,
 'aboutboul': 356,
 'aboutbut': 357,
 'aboutby': 358,
 'aboutcatscratch': 359,
 'aboutcliffhanger': 360,
 'aboutcolorful': 361,
 'aboutcombining': 362,
 'aboutcruda': 363,
 'aboutdespite': 364,
 'aboutdistant': 365,
 'aboutdont': 366,
 'aboutdustin': 367,
 'abouteven': 368,
 'aboutevery': 369,
 'abouteveryone': 370,
 'aboutface': 371,
 'aboutfirst': 372,
 'aboutfor': 373,
 'aboutfulci': 374,
 'aboutghoulies': 375,
 'aboutgorehounds': 376,
 'abouthas': 377,
 'abouthey': 378,
 'abouthowever': 379,
 'abouti': 380,
 'aboutif': 381,
 'aboutim': 382,
 'aboutimagine': 383,
 'aboutimprisoned': 384,
 'aboutin': 385,
 'aboutit': 386,
 'aboutits': 387,
 'aboutkeep': 388,
 'aboutkind': 389,
 'aboutlets': 390,
 'aboutlike': 391,
 'aboutluckily': 392,
 'aboutmake': 393,
 'aboutmy': 394,
 'aboutno': 395,
 'aboutnot': 396,
 'aboutnow': 397,
 'aboutoften': 398,
 'aboutok': 399,
 'abouton': 400,
 'aboutone': 401,
 'aboutor': 402,
 'aboutoutstanding': 403,
 'aboutoverall': 404,
 'aboutparker': 405,
 'aboutpeace': 406,
 'aboutplease': 407,
 'aboutpowerful': 408,
 'aboutprison': 409,
 'aboutprobably': 410,
 'aboutrealism': 411,
 'aboutroy': 412,
 'abouts': 413,
 'aboutsad': 414,
 'aboutsaying': 415,
 'aboutsays': 416,
 'aboutset': 417,
 'aboutsimply': 418,
 'aboutskip': 419,
 'aboutso': 420,
 'aboutsome': 421,
 'aboutstuff': 422,
 'aboutsusan': 423,
 'abouttechnically': 424,
 'aboutthat': 425,
 'aboutthe': 426,
 'aboutthen': 427,
 'aboutthere': 428,
 'aboutthey': 429,
 'aboutthis': 430,
 'aboutthursday': 431,
 'abouttobecouple': 432,
 'aboutturn': 433,
 'aboutunless': 434,
 'aboutvedmakwiedzmin': 435,
 'aboutverdictnot': 436,
 'aboutvery': 437,
 'aboutwell': 438,
 'aboutwhat': 439,
 'aboutwhen': 440,
 'aboutwithout': 441,
 'aboutyou': 442,
 'above': 443,
 'aboveaccording': 444,
 'aboveand': 445,
 'aboveaverage': 446,
 'abovebesides': 447,
 'abovedo': 448,
 'abovee': 449,
 'abovefinally': 450,
 'aboveground': 451,
 'abovei': 452,
 'abovein': 453,
 'aboveinterestingly': 454,
 'aboveit': 455,
 'aboveits': 456,
 'abovementioned': 457,
 'abovenormally': 458,
 'aboveokay': 459,
 'abovepar': 460,
 'aboveso': 461,
 'abovethe': 462,
 'abovethelaw': 463,
 'abovethis': 464,
 'abovewatch': 465,
 'abovewe': 466,
 'abra': 467,
 'abracadabrantesque': 468,
 'abraham': 469,
 'abrahamits': 470,
 'abrahamrimi': 471,
 'abrahams': 472,
 'abrahamwilliam': 473,
 'abrahimi': 474,
 'abrahms': 475,
 'abram': 476,
 'abrams': 477,
 'abraracourcix': 478,
 'abrasions': 479,
 'abrasive': 480,
 'abrasively': 481,
 'abrasiveness': 482,
 'abrazo': 483,
 'abre': 484,
 'abreast': 485,
 'abrewing': 486,
 'abrh': 487,
 'abrham': 488,
 'abridge': 489,
 'abridgedwell': 490,
 'abridgement': 491,
 'abril': 492,
 'abrils': 493,
 'abroad': 494,
 'abroadloved': 495,
 'abroadmiddletown': 496,
 'abroadsalt': 497,
 'abrogate': 498,
 'abromowitz': 499,
 'abrupt': 500,
 'abruptly': 501,
 'abruptlydirection': 502,
 'abruptness': 503,
 'abruptnessthere': 504,
 'abs': 505,
 'absalom': 506,
 'abscbn': 507,
 'abscessed': 508,
 'abscond': 509,
 'abseil': 510,
 'absence': 511,
 'absencein': 512,
 'absences': 513,
 'absencethe': 514,
 'absense': 515,
 'absent': 516,
 'absentalice': 517,
 'absentbut': 518,
 'absentee': 519,
 'absenteeism': 520,
 'absenthere': 521,
 'absentia': 522,
 'absentiaand': 523,
 'absentminded': 524,
 'absentmindedly': 525,
 'absentmindedness': 526,
 'absentmindedyetcapable': 527,
 'absentmy': 528,
 'absentoh': 529,
 'absentsubplots': 530,
 'absentthe': 531,
 'absinthe': 532,
 'abskani': 533,
 'absolom': 534,
 'absoloutely': 535,
 'absolument': 536,
 'absolute': 537,
 'absolutelly': 538,
 'absolutely': 539,
 'absolutelyconfused': 540,
 'absolutelyfantastic': 541,
 'absolutelyshame': 542,
 'absolutelyugh': 543,
 'absoluter': 544,
 'absolutey': 545,
 'absolution': 546,
 'absolutism': 547,
 'absolutlely': 548,
 'absolutley': 549,
 'absolutly': 550,
 'absolve': 551,
 'absorb': 552,
 'absorbe': 553,
 'absorbedlike': 554,
 'absorbent': 555,
 'absorbingly': 556,
 'absorption': 557,
 'absoulely': 558,
 'absoulutley': 559,
 'absoutely': 560,
 'absoutley': 561,
 'abstain': 562,
 'abstinence': 563,
 'abstinencethis': 564,
 'abstract': 565,
 'abstraction': 566,
 'abstractions': 567,
 'abstractsurrealparallel': 568,
 'abstruse': 569,
 'absurd': 570,
 'absurda': 571,
 'absurdabout': 572,
 'absurdand': 573,
 'absurdanesthesiologists': 574,
 'absurdanother': 575,
 'absurdas': 576,
 'absurdbut': 577,
 'absurddiary': 578,
 'absurder': 579,
 'absurdest': 580,
 'absurdhe': 581,
 'absurdin': 582,
 'absurdism': 583,
 'absurdismthe': 584,
 'absurdist': 585,
 'absurdities': 586,
 'absurdity': 587,
 'absurdityhere': 588,
 'absurdityif': 589,
 'absurdityit': 590,
 'absurditythe': 591,
 'absurditythere': 592,
 'absurditythis': 593,
 'absurdlooking': 594,
 'absurdly': 595,
 'absurdlydesigned': 596,
 'absurdmeyers': 597,
 'absurdness': 598,
 'absurdrenny': 599,
 'absurdsummer': 600,
 'absurdsurreal': 601,
 'absurdthat': 602,
 'absurdthe': 603,
 'absurdthis': 604,
 'absurdturning': 605,
 'absurdumwe': 606,
 'absurdyetwinning': 607,
 'abt': 608,
 'abu': 609,
 'abudantly': 610,
 'abudget': 611,
 'abuelita': 612,
 'abuelo': 613,
 'abuhabwho': 614,
 'abunch': 615,
 'abundance': 616,
 'abundanceone': 617,
 'abundancethe': 618,
 'abundant': 619,
 'abundantly': 620,
 'abundantlywithout': 621,
 'abus': 622,
 'abuse': 623,
 'abusea': 624,
 'abuseand': 625,
 'abuseat': 626,
 'abusebased': 627,
 'abusedabusive': 628,
 'abusedid': 629,
 'abusefantasticit': 630,
 'abuseheather': 631,
 'abuser': 632,
 'abusers': 633,
 'abusethe': 634,
 'abusetorture': 635,
 'abusin': 636,
 'abusive': 637,
 'abusivechitrangda': 638,
 'abusivehe': 639,
 'abusively': 640,
 'abusiveman': 641,
 'abustle': 642,
 'abusympathetic': 643,
 'abut': 644,
 'abuttment': 645,
 'abuzz': 646,
 'abvious': 647,
 'abwehr': 648,
 'aby': 649,
 'abydos': 650,
 'abynes': 651,
 'abysmal': 652,
 'abysmalalthough': 653,
 'abysmalbesides': 654,
 'abysmalit': 655,
 'abysmallistening': 656,
 'abysmally': 657,
 'abysmalthe': 658,
 'abysmalthen': 659,
 'abysmalthere': 660,
 'abyss': 661,
 'abyssits': 662,
 'abyssmal': 663,
 'abyssto': 664,
 'abysymal': 665,
 'ac': 666,
 'acacia': 667,
 'acadamy': 668,
 'acadamyhad': 669,
 'academe': 670,
 'academenyback': 671,
 'academia': 672,
 'academian': 673,
 'academic': 674,
 'academicall': 675,
 'academically': 676,
 'academics': 677,
 'academies': 678,
 'academy': 679,
 'academyaward': 680,
 'academyawardwinning': 681,
 'academycassavetes': 682,
 'academys': 683,
 'acadian': 684,
 'acadiana': 685,
 'acadmey': 686,
 'acaka': 687,
 'acandy': 688,
 'acapella': 689,
 'acapulco': 690,
 'acc': 691,
 'accapella': 692,
 'accede': 693,
 'accelerant': 694,
 'accelerate': 695,
 'acceleratedremake': 696,
 'acceleratethe': 697,
 'accelerati': 698,
 'acceleration': 699,
 'accelerator': 700,
 'accellerant': 701,
 'accent': 702,
 'accenta': 703,
 'accentall': 704,
 'accentand': 705,
 'accentbody': 706,
 'accentbut': 707,
 'accentcanned': 708,
 'accentcourtesy': 709,
 'accentdespite': 710,
 'accentdirector': 711,
 'accentedcharacters': 712,
 'accentfree': 713,
 'accenthe': 714,
 'accenthes': 715,
 'accentif': 716,
 'accentincidentally': 717,
 'accentit': 718,
 'accentits': 719,
 'accentjes': 720,
 'accentlike': 721,
 'accentnow': 722,
 'accentonly': 723,
 'accentritas': 724,
 'accentsall': 725,
 'accentsalong': 726,
 'accentsan': 727,
 'accentsas': 728,
 'accentscarecrow': 729,
 'accentseverything': 730,
 'accentsfamily': 731,
 'accentsget': 732,
 'accentsi': 733,
 'accentsif': 734,
 'accentso': 735,
 'accentsomeone': 736,
 'accentsquite': 737,
 'accentstalking': 738,
 'accentsthe': 739,
 'accentthe': 740,
 'accentthis': 741,
 'accentuate': 742,
 'accentuation': 743,
 'accentunless': 744,
 'accentyes': 745,
 'acceotable': 746,
 'accept': 747,
 'acceptability': 748,
 'acceptable': 749,
 'acceptablebut': 750,
 'acceptabledecent': 751,
 'acceptablefinally': 752,
 'acceptablefirst': 753,
 'acceptablefor': 754,
 'acceptablehitch': 755,
 'acceptableit': 756,
 'acceptablethe': 757,
 'acceptablethen': 758,
 'acceptabletheres': 759,
 'acceptabletotally': 760,
 'acceptably': 761,
 'acceptance': 762,
 'acceptances': 763,
 'acceptancethe': 764,
 'acceptand': 765,
 'acceptation': 766,
 'acceptedcarols': 767,
 'accepteddont': 768,
 'acceptedi': 769,
 'acceptedlets': 770,
 'acceptedthe': 771,
 'acceptedthus': 772,
 'acceptence': 773,
 'accepters': 774,
 'acceptgiven': 775,
 'accepti': 776,
 'acceptingly': 777,
 'acceptingthe': 778,
 'acception': 779,
 'acceptmoving': 780,
 'acceptsthey': 781,
 'acceptsthings': 782,
 'acceptswe': 783,
 'accesible': 784,
 'access': 785,
 'accessability': 786,
 'accessdogs': 787,
 'accessibility': 788,
 'accessible': 789,
 'accessibleit': 790,
 'accessibleso': 791,
 'accession': 792,
 'accessories': 793,
 'accessorizing': 794,
 'accessory': 795,
 'accessthis': 796,
 'accidences': 797,
 'accident': 798,
 'accidentaccess': 799,
 'accidentafter': 800,
 'accidental': 801,
 'accidentalchief': 802,
 'accidentally': 803,
 'accidentallypurposely': 804,
 'accidentand': 805,
 'accidentbravo': 806,
 'accidentbut': 807,
 'accidentdeath': 808,
 'accidentee': 809,
 'accidentfalon': 810,
 'accidentfans': 811,
 'accidenthe': 812,
 'accidenthis': 813,
 'accidentially': 814,
 'accidentid': 815,
 'accidentin': 816,
 'accidentit': 817,
 'accidentjane': 818,
 'accidentknowing': 819,
 'accidentlazy': 820,
 'accidently': 821,
 'accidentlying': 822,
 'accidentnot': 823,
 'accidentnow': 824,
 'accidentprobably': 825,
 'accidentprone': 826,
 'accidentrichie': 827,
 'accidents': 828,
 'accidentsampedro': 829,
 'accidentso': 830,
 'accidentsomeone': 831,
 'accidentsuicidehomicide': 832,
 'accidentsure': 833,
 'accidenttennant': 834,
 'accidentthat': 835,
 'accidentthe': 836,
 'accidentthen': 837,
 'accidentthese': 838,
 'accidentvery': 839,
 'accidentwell': 840,
 'acclaied': 841,
 'acclaim': 842,
 'acclaimall': 843,
 'acclaimit': 844,
 'acclaimthis': 845,
 'acclamation': 846,
 'acclimate': 847,
 'acclimation': 848,
 'acclimatisation': 849,
 'accolade': 850,
 'accoladed': 851,
 'accolades': 852,
 'accoladesburt': 853,
 'accoladesit': 854,
 'accomidations': 855,
 'accommodate': 856,
 'accommodation': 857,
 'accommodations': 858,
 'accomodates': 859,
 'accomodations': 860,
 'accompagnied': 861,
 'accompaniment': 862,
 'accompanist': 863,
 'accompany': 864,
 'accompanythe': 865,
 'accomplice': 866,
 'accomplices': 867,
 'accomplicethese': 868,
 'accomplish': 869,
 'accomplishedas': 870,
 'accomplishedi': 871,
 'accomplishedjulie': 872,
 'accomplishedsecondly': 873,
 'accomplishedwhat': 874,
 'accomplishfonda': 875,
 'accomplishi': 876,
 'accomplishment': 877,
 'accomplishmentits': 878,
 'accomplishmentone': 879,
 'accomplishments': 880,
 'accomplishmentslaurent': 881,
 'accomplishmentso': 882,
 'accomplishpeter': 883,
 'accomplishthe': 884,
 'accord': 885,
 'accordance': 886,
 'accordedthe': 887,
 'accordian': 888,
 'accordingly': 889,
 'accordinglycertainly': 890,
 'accordinglyhence': 891,
 'accordinglyin': 892,
 'accordinglynow': 893,
 'accordinglysean': 894,
 'accordinglyshe': 895,
 'accordinglythat': 896,
 'accordinglythe': 897,
 'accordinglythis': 898,
 'accordinglywatch': 899,
 'accordingto': 900,
 'accordion': 901,
 'accordionistvocalist': 902,
 'accordionlike': 903,
 'accordsecondly': 904,
 'accorsi': 905,
 'accoss': 906,
 'accost': 907,
 'account': 908,
 'accountability': 909,
 'accountable': 910,
 'accountancy': 911,
 'accountand': 912,
 'accountant': 913,
 'accountantembezzler': 914,
 'accountants': 915,
 'accountinglynch': 916,
 'accountsfirst': 917,
 'accountsmaybe': 918,
 'accountsmilos': 919,
 'accountsthe': 920,
 'accountsynopsis': 921,
 'accountthe': 922,
 'accountwerners': 923,
 'accountyeh': 924,
 'accouterments': 925,
 'accoutrements': 926,
 'accowmplished': 927,
 'accredit': 928,
 'accross': 929,
 'accrue': 930,
 'accrutements': 931,
 'acct': 932,
 'acculturation': 933,
 'accumulate': 934,
 'accumulation': 935,
 'accumulator': 936,
 'accuracies': 937,
 'accuracy': 938,
 'accuracybutin': 939,
 'accuracyespecially': 940,
 'accuracyness': 941,
 'accuracyone': 942,
 'accuracythe': 943,
 'accuracythis': 944,
 'accurate': 945,
 'accuratea': 946,
 'accurateactually': 947,
 'accuratebut': 948,
 'accuratehenry': 949,
 'accuratei': 950,
 'accurateif': 951,
 'accurateits': 952,
 'accurateloosen': 953,
 'accurately': 954,
 'accuratelymaybe': 955,
 'accuratemiramax': 956,
 'accurateof': 957,
 'accurateput': 958,
 'accuratethen': 959,
 'accuratevery': 960,
 'accurse': 961,
 'accusation': 962,
 'accusationoverall': 963,
 'accusations': 964,
 'accusationswatch': 965,
 'accusatory': 966,
 'accuse': 967,
 'accuseds': 968,
 'accusee': 969,
 'accuser': 970,
 'accusers': 971,
 'accussation': 972,
 'accussed': 973,
 'accustom': 974,
 'accustomedfirst': 975,
 'accutely': 976,
 'acczent': 977,
 'acd': 978,
 'acdc': 979,
 'acdcs': 980,
 'acds': 981,
 'ace': 982,
 'acedemy': 983,
 'acedmy': 984,
 'acehal': 985,
 'acerbic': 986,
 'acerbity': 987,
 'acesiron': 988,
 'acetylene': 989,
 'aceves': 990,
 'ach': 991,
 'achaar': 992,
 'achad': 993,
 'achala': 994,
 'achance': 995,
 'achangin': 996,
 'acharya': 997,
 'acharyas': 998,
 'achcha': 999,
 ...}

In [80]:
def one_hot_encoding(word2idx, word, vocab):
    vector = np.zeros(len(vocab))
    vector[word2idx[word]] = 1

    return vector

X = []

for w in df["clean_text"][1].split():
    vec = np.array(one_hot_encoding(word2idx, w, vocab))
    X.append(vec)

print(X)

# for text in df["clean_text"]:
#     for w in text.split():
#         vec = np.array(one_hot_encoding(word2idx, w, vocab))
#         X.append(vec)

[array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.])]

In [81]:
df.to_csv("processed.csv")